language: node_js
node_js:
  - 6
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm test
after_success:
  - mv build/index.html build/200.html
<<<<<<< HEAD
  - surge --project ./build --domain react-dash.surge.sh
=======
  - surge --project ./build --domain react-dash-2.surge.sh
>>>>>>> Fix typo in Timer preventing proper reset
